version: "3.5"

services:

  esdb-single-node:
   image: eventstore/eventstore:20.10.0-buster-slim
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_ADVERTISE_HTTP_PORT_TO_CLIENT_AS=2113
     - EVENTSTORE_ADVERTISE_TCP_PORT_TO_CLIENT_AS=1113
   ports:
     - 1113:1113
     - 2113:2113
   volumes:
  #    - "~/Data/eventstore/singlenode:/var/lib/eventstore"
      - "./certificates/ca:/opt/eventstore/ca"
      - "./certificates/server:/opt/eventstore/cert"
   restart: always
   networks:
     clusternetwork:
       ipv4_address: 172.16.0.11

networks:
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
